# Root config — loaded by all child units via find_in_parent_folders("root.hcl")
#
# Directory hierarchy: <account>/<region>/<environment>/<module>/terragrunt.hcl
# Three config layers resolved via find_in_parent_folders():
#   account.hcl  → account identity / auth profile name
#   region.hcl   → BaiduCloud region (bj, su, gz, ...)
#   env.hcl      → environment name, project name

locals {
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  env_vars     = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  account_name = local.account_vars.locals.account_name
  region       = local.region_vars.locals.region
  env          = local.env_vars.locals.environment
  project      = local.env_vars.locals.project

  # BOS bucket for remote state (create once outside Terraform)
  state_bucket = "${local.project}-tfstate"

  # Optional endpoint override for BOS S3-compatible API used by backend "s3"
  bos_endpoint = get_env("BAIDUCLOUD_BOS_ENDPOINT", "https://s3.${local.region}.bcebos.com")
}

# Remote state via BOS (S3-compatible). Create the bucket once before first init.
# See: https://cloud.baidu.com/doc/BOS/s/Zjwvyq3of
remote_state {
  backend = "s3"

  disable_dependency_optimization = true

  config = {
    bucket                      = local.state_bucket
    key                         = "${local.region}/${local.env}/${path_relative_to_include()}/terraform.tfstate"
    region                      = local.region
    endpoint                    = local.bos_endpoint
    encrypt                     = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    force_path_style            = true
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

terraform {
  extra_arguments "init_reconfigure" {
    commands  = ["init"]
    arguments = ["-reconfigure"]
  }
}

generate "provider" {
  path      = "provider_tg.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOT
    # Generated by Terragrunt — do not edit manually.
    provider "baiducloud" {
      region = "${local.region}"
    }
  EOT
}

inputs = {
  project     = local.project
  environment = local.env
  tags = {
    Project     = local.project
    Environment = local.env
    Account     = local.account_name
    Region      = local.region
    ManagedBy   = "terraform"
  }
}
